site_name: PSCodeHealth
repo_url: https://github.com/MathieuBuisson/PSCodeHealth
site_author: Mathieu Buisson
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PSCodeHealth is licensed under the <a href='https://github.com/MathieuBuisson/PSCodeHealth/raw/master/LICENSE.md'>MIT license"
pages:
  - Home: index.md
  - Installation: Installation.md
  - Release Notes: Release.md
  - Getting Started: GettingStarted.md
  - Metrics collected by PSCodeHealth: Metrics.md
  - How do I ...:
    - Check if my code meets metrics goals: HowDoI/CheckCodeCompliance.md
    - Customize compliance rules according to my metrics goals: HowDoI/CustomizeComplianceRules.md
